# Make the prototypes project.

all:
	@echo "Making common..."
	@(cd src/common; make)
	@echo "Making mona..."
	@(cd src/mona; make)
	@echo "Making ant..."
	@(cd src/ant; make)
	@echo "Making nest..."
	@(cd src/nest; make)
	@echo "Making java..."
	@(cd src/java; make)
	@echo "done"

clean:
	(cd src/common; make clean)
	(cd src/mona; make clean)
	(cd src/ant; make clean)
	(cd src/nest; make clean)
	(cd src/java; make clean)
