# Make the maze project.

all:
	@echo "Making common..."
	@(cd src/common; make)
	@echo "Making mona..."
	@(cd src/mona; make)
	@echo "Making maze..."
	@(cd src/maze; make)
	@echo "done"

clean:
	(cd src/common; make clean)
	(cd src/mona; make clean)
	(cd src/maze; make clean)

