/* include/allegro/platform/alunixac.h.  Generated by configure.  */
/* include/allegro/platform/alunixac.hin.  Generated from configure.in by autoheader.  */

/* Define to the installed ALSA version. */
/* #undef ALLEGRO_ALSA_VERSION */

/* Define if compiler prepends underscore to symbols. */
/* #undef ALLEGRO_ASM_PREFIX */

/* Define if target machine is big endian. */
#define ALLEGRO_BIG_ENDIAN 1

/* Define if you want support for 16 bpp modes. */
#define ALLEGRO_COLOR16 1

/* Define if you want support for 24 bpp modes. */
#define ALLEGRO_COLOR24 1

/* Define if you want support for 32 bpp modes. */
#define ALLEGRO_COLOR32 1

/* Define if you want support for 8 bpp modes. */
#define ALLEGRO_COLOR8 1

/* Define if target platform is Darwin. */
/* #undef ALLEGRO_DARWIN */

/* Define to 1 if you have getexecname */
#define ALLEGRO_HAVE_GETEXECNAME 1

/* Define to 1 if procfs reveals argc and argv */
#define ALLEGRO_HAVE_PROCFS_ARGCV 1

/* Define to 1 if you have a System V sys/procfs.h */
#define ALLEGRO_HAVE_SV_PROCFS 1

/* Define if target platform is linux. */
/* #undef ALLEGRO_LINUX */

/* Define to enable Linux console fbcon driver. */
/* #undef ALLEGRO_LINUX_FBCON */

/* Define to enable Linux console SVGAlib driver. */
/* #undef ALLEGRO_LINUX_SVGALIB */

/* Define if SVGAlib driver can check vga_version. */
/* #undef ALLEGRO_LINUX_SVGALIB_HAVE_VGA_VERSION */

/* Define to enable Linux console VBE/AF driver. */
/* #undef ALLEGRO_LINUX_VBEAF */

/* Define to enable Linux console VGA driver. */
/* #undef ALLEGRO_LINUX_VGA */

/* Define if target machine is little endian. */
/* #undef ALLEGRO_LITTLE_ENDIAN */

/* Define if assembler supports MMX. */
/* #undef ALLEGRO_MMX */

/* Define for Unix platforms, to use C convention for bank switching. */
#define ALLEGRO_NO_ASM 1

/* Define if assembler supports SSE. */
/* #undef ALLEGRO_SSE */

/* Define if constructor attribute is supported. */
#define ALLEGRO_USE_CONSTRUCTOR 1

/* Define if sched_yield is provided by some library. */
#define ALLEGRO_USE_SCHED_YIELD 1

/* Define if XIM extension is supported. */
#define ALLEGRO_USE_XIM 1

/* Define if ALSA DIGI driver is supported. */
/* #undef ALLEGRO_WITH_ALSADIGI */

/* Define if ALSA MIDI driver is supported. */
/* #undef ALLEGRO_WITH_ALSAMIDI */

/* Define if aRts DIGI driver is supported. */
/* #undef ALLEGRO_WITH_ARTSDIGI */

/* Define if ESD DIGI driver is supported. */
#define ALLEGRO_WITH_ESDDIGI 1

/* Define if JACK DIGI driver is supported. */
/* #undef ALLEGRO_WITH_JACKDIGI */

/* Define if you need to use a magic main. */
/* #undef ALLEGRO_WITH_MAGIC_MAIN */

/* Define if dynamically loaded modules are supported. */
/* #undef ALLEGRO_WITH_MODULES */

/* Define if OSS DIGI driver is supported. */
/* #undef ALLEGRO_WITH_OSSDIGI */

/* Define if OSS MIDI driver is supported. */
/* #undef ALLEGRO_WITH_OSSMIDI */

/* Define if SGI AL DIGI driver is supported. */
/* #undef ALLEGRO_WITH_SGIALDIGI */

/* Define if you need support for X-Windows. */
#define ALLEGRO_WITH_XWINDOWS 1

/* Define if MIT-SHM extension is supported. */
#define ALLEGRO_XWINDOWS_WITH_SHM 1

/* Define if XCursor ARGB extension is available. */
/* #undef ALLEGRO_XWINDOWS_WITH_XCURSOR */

/* Define if DGA version 2.0 or newer is supported */
/* #undef ALLEGRO_XWINDOWS_WITH_XF86DGA2 */

/* Define if XF86VidMode extension is supported. */
/* #undef ALLEGRO_XWINDOWS_WITH_XF86VIDMODE */

/* Define if xpm bitmap support is available. */
#define ALLEGRO_XWINDOWS_WITH_XPM 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `ossaudio' library (-lossaudio). */
/* #undef HAVE_LIBOSSAUDIO */

/* Define if you have the pthread library. */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <linux/awe_voice.h> header file. */
/* #undef HAVE_LINUX_AWE_VOICE_H */

/* Define to 1 if you have the <linux/input.h> header file. */
/* #undef HAVE_LINUX_INPUT_H */

/* Define to 1 if you have the <linux/joystick.h> header file. */
/* #undef HAVE_LINUX_JOYSTICK_H */

/* Define to 1 if you have the <linux/soundcard.h> header file. */
/* #undef HAVE_LINUX_SOUNDCARD_H */

/* Define to 1 if you have the <machine/soundcard.h> header file. */
/* #undef HAVE_MACHINE_SOUNDCARD_H */

/* Define to 1 if you have the `memcmp' function. */
#define HAVE_MEMCMP 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the `mmap' function. */
#define HAVE_MMAP 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <soundcard.h> header file. */
/* #undef HAVE_SOUNDCARD_H */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `stricmp' function. */
/* #undef HAVE_STRICMP */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strlwr' function. */
/* #undef HAVE_STRLWR */

/* Define to 1 if you have the `strupr' function. */
/* #undef HAVE_STRUPR */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/io.h> header file. */
/* #undef HAVE_SYS_IO_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
/* #undef HAVE_SYS_SOUNDCARD_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to (void *)-1, if MAP_FAILED is not defined. */
/* #undef MAP_FAILED */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#define TIME_WITH_SYS_TIME 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
#define WORDS_BIGENDIAN 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
