# Make the instinct project.

all:
	@echo "Making common..."
	@(cd src/common; make)
	@echo "Making mona..."
	@(cd src/mona; make)
	@echo "Making instinct..."
	@(cd src/instinct; make)
	@echo "done"

clean:
	(cd src/common; make clean)
	(cd src/mona; make clean)
	(cd src/instinct; make clean)

