/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mona_NativeFileDescriptor */

#ifndef _Included_mona_NativeFileDescriptor
#define _Included_mona_NativeFileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mona_NativeFileDescriptor
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mona_NativeFileDescriptor_open
  (JNIEnv *, jobject);

/*
 * Class:     mona_NativeFileDescriptor
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_mona_NativeFileDescriptor_close
  (JNIEnv *, jobject);

/*
 * Class:     mona_NativeFileDescriptor
 * Method:    seek
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_mona_NativeFileDescriptor_seek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mona_NativeFileDescriptor
 * Method:    tell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_mona_NativeFileDescriptor_tell
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
